<?php

/**
 * Language strings.
 *
 * @package tool_ilioscategoryassignment
 */

$string['apikey'] = 'Ilios API key';
$string['apikey_desc'] = 'Enter the API key obtained from your Ilios server.';
$string['clientconfig'] = "Ilios API client configuration";
$string['clientconfig_desc'] = "Configure your Ilios API endpoint and credentials here.";
$string['deletejob'] = "Delete sync job";
$string['deletejobconfirm'] = 'You are about to delete the Ilios category assignment sync job "{$a->jobtitle}". All users currently assigned as course participants in the "{$a->roletitle}" role to courses in the "{$a->coursecattitle}" course category using this method will be removed.<br><br>Are you sure you want to continue?';
$string['host_url'] = 'Host URL';
$string['host_url_desc'] = 'Type Ilios server IP address or host URL.';
$string['ilioserror'] =
    'An error occurred while accessing Ilios. Please check that Ilios is up and running, and that your connection to Ilios is configured correctly.';
$string['iliosschool'] = 'Ilios school';
$string['jobenabled'] = 'Enabled sync job "{$a}".';
$string['jobdeleted'] = 'Deleted sync job "{$a}".';
$string['jobdisabled'] = 'Disabled sync job "{$a}".';
$string['newjobcreated'] = 'Created new sync job "{$a}".';
$string['newsyncjob'] = "New sync job";
$string['noassignablecategories'] = 'There are currently no course categories that can be used for assignment.';
$string['noassignableroles'] = 'There are currently no roles that can be used for assignment.';
$string['notfound'] = '[[ not found (id = {$a} ]]';
$string['pluginname'] = 'Ilios category assignment';
$string['secret'] = 'Ilios secret';
$string['secret_desc'] = 'Enter the secret string generated by your Ilios server here.';
$string['selectcategory'] = 'Select category';
$string['selectiliosschool'] = 'Select Ilios school';
$string['selectrole'] = 'Select role';
$string['syncjobs'] = 'Sync jobs';
$string['syncjobscount'] = 'Sync jobs ({$a})';
$string['taskname'] = 'Sync category role assignments against Ilios';
$string['title'] = 'Title';
$string['userid'] = 'Ilios user ID';
$string['userid_desc'] = 'Enter the user ID to be used to contact the Ilios server here.';

