<?php

/**
 * Language strings.
 *
 * @package tool_ilioscategoryassignment
 */

$string['apikey'] = 'Ilios API key';
$string['apikey_desc'] = 'Enter the API key obtained from your Ilios server.';
$string['clientconfig'] = "Ilios API client configuration";
$string['clientconfig_desc'] = "Configure your Ilios API endpoint and credentials here.";
$string['host_url'] = 'Host URL';
$string['host_url_desc'] = 'Type Ilios server IP address or host URL.';
$string['pluginname'] = 'Ilios category assignment';
$string['secret'] = 'Ilios secret';
$string['secret_desc'] = 'Enter the secret string generated by your Ilios server here.';
$string['taskname'] = 'Sync category role assignments against Ilios roles';
$string['userid'] = 'Ilios user ID';
$string['userid_desc'] = 'Enter the user ID to be used to contact the Ilios server here.';

